## realTrails.R
## R script file to analyze / plot files generated by chuck program trails.ck 
## containing inputs from a given user

## warning: comment lines are lead by two ##, code lines by one # (when commented)

## working with....
## self generated: out2221000.txt, out222nnnn.txt, with chuck/miniAudicle trails.ck file
## in your local drive
## numbers after "out....", if even are from random seeded inputs; if odd, otherwise

## check working directory 
getwd()

## uncomment and change as desired. For example... where your .txt files are located
## follow convention after previous (getwd()) command
## for example....
##setwd("~/Documents/MuseScore3/Partituras/chuck/dasher/kadensze_sess1")
setwd("/Users/gerardogarciacabrero/Desktop/DasherSpasms")

## uncomment and change as required. "out222xxxx.txt" change xxxx with 1000,1001...1nnn
## for example...
ratonera <- read.table("out2221028.txt", header = TRUE, sep = ",") 

library(dplyr)
library(ggplot2)
library(ggrepel)
set.seed(42)

## text file numbers (...30.txt, ...31.txt) by the Chuck script
## when odd, generate different buttons map. If from-even maps
## are not exactly the same, the clicks on the buttons might have
## been repeated, out of sync, or off the buttons. Traces, anyhow,
## may be valid, even if some clicks (syllables) are missing.
qplot(X, -Y, data = ratonera, main = "Even file # (AND 1 click per button) == constant map", color = SYLLABLE)
qplot(cX, cY, data = ratonera, main = "Trails from mouse position to next button click", color = SYLLABLE)

qplot(dX, data = ratonera, color = SYLLABLE, geom = "density")
qplot(-dY, data = ratonera, color = SYLLABLE, geom = "density")

## next code sections are optional exploratory commands for whole text file or SYLLABLE trail subsets  

fray1 <- filter(ratonera, SYLLABLE == "FRAY 1")
qplot(cX, cY, data = fray1, color = "FRAY 1" ,geom = "point" )
qplot(cX, cY, data = fray1, color = "FRAY 1" ,geom = c("point", "smooth") )
qplot(dX, data = fray1, color = SYLLABLE, geom = "density")
qplot(-dY, data = fray1, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = fray1, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = fray1, color = SYLLABLE, geom = "line")

qplot(dX, -dY, data = fray1, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


san2 <- filter(ratonera, SYLLABLE == "SAN- 2")
qplot(dX, data = san2, color = SYLLABLE, geom = "density")
qplot(-dY, data = san2, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = san2, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = san2, color = SYLLABLE, geom = "line")

qplot(dX, -dY, data = san2, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


tia3 <- filter(ratonera, SYLLABLE == "-TIA- 3")
qplot(dX, data = tia3, color = SYLLABLE, geom = "density")
qplot(-dY, data = tia3, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = tia3, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = tia3, color = SYLLABLE, geom = "line")

qplot(dX, -dY, data = tia3, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


go4 <- filter(ratonera, SYLLABLE == "GO 4")
qplot(dX, data = go4, color = SYLLABLE, geom = "density")
qplot(-dY, data = go4, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = go4, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = go4, color = SYLLABLE, geom = "line")

qplot(dX, -dY, data = go4, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


fray5 <- filter(ratonera, SYLLABLE == "FRAY 5")
qplot(dX, data = fray5, color = SYLLABLE, geom = "density")
qplot(-dY, data = fray5, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = fray5, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = fray5, color = SYLLABLE, geom = "line")

san6 <- filter(ratonera, SYLLABLE == "SAN- 6")
qplot(dX, data = san6, color = SYLLABLE, geom = "density")
qplot(-dY, data = san6, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = san6, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = san6, color = SYLLABLE, geom = "line")

tia7 <- filter(ratonera, SYLLABLE == "-TIA- 7")
qplot(dX, data = tia7, color = SYLLABLE, geom = "density")
qplot(-dY, data = tia7, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = tia7, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = tia7, color = SYLLABLE, geom = "line")

go8 <- filter(ratonera, SYLLABLE == "GO 8")
qplot(dX, data = go8, color = SYLLABLE, geom = "density")
qplot(-dY, data = go8 , color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, dX, data = go8, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = go8, color = SYLLABLE, geom = "line")

#qplot(dX, data = ratonera, color = "SYLLABLE", geom = "density" )
#qplot(-dY, data = ratonera, color = "SYLLABLE", geom = "density" )

#qplot(dX, WHEN, data = ratonera, color = SYLLABLE)
#qplot(-dY, WHEN, data = ratonera, color = SYLLABLE)

qplot(WHEN * 1000, dX, data = ratonera, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -dY, data = ratonera, color = SYLLABLE, geom = "line")

qplot(WHEN * 1000, dX, data = ratonera, color = "SYLLABLE", geom = "line")
qplot(WHEN * 1000, -dY, data = ratonera, color = "SYLLABLE", geom = "line")


qplot(dX, -dY, data = ratonera, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'
 qplot(dX, -dY, data = ratonera, color = SYLLABLE, geom = c("line", "smooth"))
+ `geom_smooth()` using method = 'loess' and formula '-y ~ x'

 qplot(dX, -dY, data = fray1, color = SYLLABLE, geom = c("line", "smooth"))
 + `geom_smooth()` using method = 'loess' and formula '-y ~ x'
 
 
summary(ratonera)

#ratonera <- read.table("out222.txt", header = TRUE, sep = ",")
abrat <- read.table("out222.txt", header = TRUE, sep = ",")
head(abrat)

abrat$dXabs = abs(ratonera$dX)
tail(abrat)

abrat$dYabs = abs(ratonera$dY)
tail(abrat)

abratAbsx <- sum(abrat$dXabs)
abratAbsx 

abratAbsy <- sum(abrat$dYabs)
abratAbsy 

manhatan <- abratAbsx + abratAbsy
manhatan



