## realTrails.R
## R script file to analyze / plot files generated by chuck program trails.ck 
## containing inputs from a given user

## warning: comment lines are lead by two ##, code lines by one # (when commented)

## working with....
## self generated: out2221000.txt, out222nnnn.txt, with chuck/miniAudicle trails.ck file
## in your local drive
## numbers after "out....", if even are from random seeded inputs; if odd, otherwise

## check working directory 
getwd()

## uncomment and change as desired. For example... where your .txt files are located
## follow convention after previous (getwd()) command
## for example....
##setwd("~/Documents/MuseScore3/Partituras/chuck/dasher/kadensze_sess1")
setwd("/Users/gerardogarciacabrero/Desktop/DasherSpasms")

## uncomment and change as required. "out222xxxx.txt" change xxxx with 1000,1001...1nnn
## for example...
ratonera <- read.table("out2221041.txt", header = TRUE, sep = ",") 

library(dplyr)
library(ggplot2)
library(ggrepel)
set.seed(42)

## text file numbers (...30.txt, ...31.txt) by the Chuck script
## when odd, generate different buttons map. If from-even maps
## are not exactly the same, the clicks on the buttons might have
## been repeated, out of sync, or off the buttons. Traces, anyhow,
## may be valid, even if some clicks (syllables) are missing.
qplot(XofButton, -YofButton, data = ratonera, main = "Even file # (AND 1 click per button) == constant map", color = SYLLABLE)
qplot(XofTrace, YofTrace, data = ratonera, main = "Trails from mouse position to next button click", color = SYLLABLE)

qplot(deltaX, data = ratonera, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = ratonera, color = SYLLABLE, geom = "density")

## next code sections are optional exploratory commands for whole text file or SYLLABLE trail subsets  

fray1 <- filter(ratonera, SYLLABLE == "FRAY 1")
## plot of segment
qplot(XofTrace, YofTrace, data = fray1, color = "FRAY 1")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(fray1,1)
tail(fray1,1)
qplot(deltaX, data = fray1, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = fray1, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = fray1, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = fray1, color = SYLLABLE, geom = "line")

qplot(deltaX, -deltaY, data = fray1, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


san2 <- filter(ratonera, SYLLABLE == "SAN- 2")
## plot of segment
qplot(XofTrace, YofTrace, data = san2, color = "SAN- 2")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(san2,1)
tail(san2,1)
qplot(deltaX, data = san2, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = san2, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = san2, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = san2, color = SYLLABLE, geom = "line")

qplot(deltaX, -deltaY, data = san2, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


tia3 <- filter(ratonera, SYLLABLE == "-TIA- 3")
## plot of segment
qplot(XofTrace, YofTrace, data = tia3, color = "-TIA- 3")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(tia3,1)
tail(tia3,1)
qplot(deltaX, data = tia3, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = tia3, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = tia3, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = tia3, color = SYLLABLE, geom = "line")

qplot(deltaX, -deltaY, data = tia3, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


go4 <- filter(ratonera, SYLLABLE == "GO 4")
## plot of segment
qplot(XofTrace, YofTrace, data = go4, color = "GO 4")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(go4,1)
tail(go4,1)
qplot(WHEN * 1000, deltaX, data = go4, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = go4, color = SYLLABLE, geom = "line")

qplot(deltaX, -deltaY, data = go4, color = SYLLABLE, geom = c("point", "smooth")) 
+ `geom_smooth()` using method = 'loess' and formula 'y ~ x'


fray5 <- filter(ratonera, SYLLABLE == "FRAY 5")
## plot of segment
qplot(XofTrace, YofTrace, data = fray5, color = "FRAY 5")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(fray5,1)
tail(fray5,1)
qplot(deltaX, data = fray5, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = fray5, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = fray5, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = fray5, color = SYLLABLE, geom = "line")

san6 <- filter(ratonera, SYLLABLE == "SAN- 6")
## plot of segment
qplot(XofTrace, YofTrace, data = san6, color = "SAN- 6")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(san6,1)
tail(san6,1)
qplot(deltaX, data = san6, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = san6, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = san6, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = san6, color = SYLLABLE, geom = "line")

tia7 <- filter(ratonera, SYLLABLE == "-TIA- 7")
## plot of segment
qplot(XofTrace, YofTrace, data = tia7, color = "-TIA- 7")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(tia7,1)
tail(tia7,1)
qplot(deltaX, data = tia7, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = tia7, color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = tia7, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = tia7, color = SYLLABLE, geom = "line")

go8 <- filter(ratonera, SYLLABLE == "GO 8")
## plot of segment
qplot(XofTrace, YofTrace, data = go8, color = "GO 8")
## beggining and ending of trace coordinates (XofTrace, YofTrace)
head(go8,1)
tail(go8,1)
qplot(deltaX, data = go8, color = SYLLABLE, geom = "density")
qplot(-deltaY, data = go8 , color = SYLLABLE, geom = "density")
qplot(WHEN * 1000, deltaX, data = go8, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = go8, color = SYLLABLE, geom = "line")


qplot(deltaX, WHEN, data = ratonera, color = SYLLABLE)
qplot(-deltaY, WHEN, data = ratonera, color = SYLLABLE)

qplot(WHEN * 1000, deltaX, data = ratonera, color = SYLLABLE, geom="line")
qplot(WHEN * 1000, -deltaY, data = ratonera, color = SYLLABLE, geom = "line")

qplot(WHEN * 1000, deltaX, data = ratonera, color = "SYLLABLE", geom = "line")
qplot(WHEN * 1000, -deltaY, data = ratonera, color = "SYLLABLE", geom = "line")

summary(ratonera)

abrat <- ratonera
head(abrat)

abrat$deltaXabs = abs(ratonera$deltaX)
tail(abrat)

abrat$deltaYabs = abs(ratonera$deltaY)
tail(abrat)

abratAbsx <- sum(abrat$deltaXabs)
abratAbsx 

abratAbsy <- sum(abrat$deltaYabs)
abratAbsy 

manhatan <- abratAbsx + abratAbsy
manhatan


