## realTrails.R
## R script file to analyze / plot files generated by chuck program trails.ck 
## containing inputs from a given user....

## warning: comment lines are lead by two ##, code lines by one # (when commented)

## working with....
## self generated: out2221000.txt, out222nnnn.txt, with chuck/miniAudicle trails.ck file
## in your local drive
## numbers after "out....", if even are from random seeded inputs; if odd, otherwise

## check working directory 
getwd()

## uncomment and change as desired. For example... where your .txt files are located
## follow convention after previous (getwd()) command
## for example....
##setwd("~/Documents/MuseScore3/Partituras/chuck/dasher/kadensze_sess1")
setwd("/Users/gerardogarciacabrero/Desktop/DasherSpasms")

## uncomment and change as required. "out222xxxx.txt" change xxxx with 1000,1001...1nnn
## for example...
ratonera <- read.table("out2221560.txt", header = TRUE, sep = ",") 

library(dplyr)
library(ggplot2)
library(ggrepel)
set.seed(42)
options(ggrepel.max.overlaps = Inf)
options(scipen = 999)

ratonera <-  ratonera %>%  mutate(YofTblazer = YofTblazer * -1)
## text file numbers (...30.txt, ...31.txt) by the Chuck script
## when odd, generate different buttons map. If from-even maps
## are not exactly the same, the clicks on the buttons might have
## been repeated, out of sync, or off the buttons. Traces, anyhow,
## may be valid, even if some clicks (syllables) are missing.
qplot(XofButton, -YofButton, data = ratonera, main = "Even file # (AND 1 click per button) == constant map", color = SYLLABLE)
qplot(XofTrace, YofTrace, data = ratonera, main = "Trails from mouse position to next button click", color = SYLLABLE)
qplot(XofTblazer, YofTblazer, data = ratonera, main = "Trails from mouse position to next button click", color = SYLLABLE)

 ## next code sections are optional exploratory commands for whole text file or SYLLABLE trail subsets  

fray1 <- filter(ratonera, SYLLABLE == "SAN- 6")
## plot of segment
qplot(XofTrace, YofTrace, data = fray1, color = "FRAY 1")


#*****

san6_in_ratonera <- filter(ratonera, SYLLABLE == "FRAY 5")
san6_in_ratonera_diffs <- san6_in_ratonera %>%  mutate(when_diff = WHEN - lag(WHEN))
san6_in_ratonera_diffs <- san6_in_ratonera_diffs %>% mutate(ladiff = exp(when_diff))
id <-rownames(san6_in_ratonera_diffs)
san6_in_ratonera_diffs <- cbind(id=id, san6_in_ratonera_diffs)
head(san6_in_ratonera_diffs, 2)
tail(san6_in_ratonera_diffs, 1)


p <- ggplot(san6_in_ratonera_diffs, aes(x=XofTblazer, y=YofTblazer))
p +  geom_count(mapping=aes(color=ifelse(when_diff < 0.01,  
                substr(when_diff,1,6), NA), size = .5)) +
  scale_y_continuous(limits = 
    c(min(san6_in_ratonera_diffs[,"YofTblazer"]), 
          max(san6_in_ratonera_diffs[,"YofTblazer"])), 
          breaks = seq(min(san6_in_ratonera_diffs[,"YofTblazer"]), 
          max(san6_in_ratonera_diffs[,"YofTblazer"]), by = 50)) +
  scale_x_continuous(limits = 
    c(min(san6_in_ratonera_diffs[,"XofTblazer"]), 
          max(san6_in_ratonera_diffs[,"XofTblazer"])), 
          breaks = seq(min(san6_in_ratonera_diffs[,"XofTblazer"]), 
          max(san6_in_ratonera_diffs[,"XofTblazer"]), by = 50)) +
  scale_colour_discrete("Time spans") +
  labs(title = "San 6 del 1067, < 0.006, 29 y 31 mismas coordenadas") +
  labs(x = "Horizontal mouse movement magnitudes", 
       y = "Vertical mouse movement magnitudes", 
       caption = "SAN- 6 segment from file out2221067.txt Observación 28 con coordendas")+
  geom_text_repel(min.segment.length = 0,
       size = 3.5,aes(label=ifelse(when_diff < 0.01, 
      paste((id),"(",XofTblazer,",",YofTblazer,")"),paste(id))))


p <- ggplot(san6_in_ratonera_diffs, aes(x=YofTrace, y=YofTrace))
p +  geom_count(mapping=aes(color=ifelse(when_diff < 0.01,  
                                         substr(when_diff,1,6), NA), size = .5)) +
  scale_y_continuous(limits = 
                       c(min(san6_in_ratonera_diffs[,"YofTrace"]), 
                         max(san6_in_ratonera_diffs[,"YofTrace"])), 
                     breaks = seq(min(san6_in_ratonera_diffs[,"YofTrace"]), 
                                  max(san6_in_ratonera_diffs[,"YofTrace"]), by = 50)) +
  scale_x_continuous(limits = 
                       c(min(san6_in_ratonera_diffs[,"YofTrace"]), 
                         max(san6_in_ratonera_diffs[,"YofTrace"])), 
                     breaks = seq(min(san6_in_ratonera_diffs[,"YofTrace"]), 
                                  max(san6_in_ratonera_diffs[,"YofTrace"]), by = 50)) +
  scale_colour_discrete("Time spans") +
  labs(title = "San 6 del 1067, < 0.006, 29 y 31 mismas coordenadas") +
  labs(x = "Horizontal mouse movement magnitudes", 
       y = "Vertical mouse movement magnitudes", 
       caption = "SAN- 6 segment from file out2221067.txt Observación 28 con coordendas")+
  geom_text_repel(min.segment.length = 0,
                  size = 3.5,aes(label=ifelse(when_diff < 0.01, 
                                              paste((id),"(",YofTrace,",",YofTrace,")"),paste(id))))



#*****

q <- ggplot(san6_in_ratonera_diffs, aes(x=XofTrace, y=YofTrace))
q +  geom_count(mapping=aes(color=ifelse(exp(when_diff) < 1.0009, substr(ladiff,1,12), NA)), size = 3, alpha=2)+
  scale_y_continuous(limits = c(min(san6_in_ratonera_diffs[,"YofTrace"]), max(san6_in_ratonera_diffs[,"YofTrace"])), breaks = seq(min(san6_in_ratonera_diffs[,"YofTrace"]), max(san6_in_ratonera_diffs[,"YofTrace"]), by = 20)) +
  scale_x_continuous(limits = c(min(san6_in_ratonera_diffs[,"XofTrace"]), max(san6_in_ratonera_diffs[,"XofTrace"])), breaks = seq(min(san6_in_ratonera_diffs[,"XofTrace"]), max(san6_in_ratonera_diffs[,"XofTrace"]), by = 10)) +
  scale_colour_discrete("Time spans") +
  labs(title = "San 6 from out2221067. Time spans < 1.0009 include all observations ") +
  labs(x = "Horizontal mouse movement magnitudes", y = "Vertical mouse movement magnitudes", 
       caption = "SAN- 6 segment from file out2221067.txt con todas las diferencias desde el punto anterior. El 31 en 006793, el más lento. El 28 el más rápido")+
  geom_text_repel(min.segment.length = 0,
                  size = 3.5,aes(label=ifelse(exp(when_diff) < 1.0009, paste(id,"[", substr(ladiff,4,9)),paste(id))))

 